<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Cheetah\\Config\\ConfigInterface' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            $config_factory = $c->get(\Cheetah\Config\ConfigFactory::class);
            return $config_factory($c);
        }, 'Cheetah\\Config\\ConfigInterface');
    }

}
